name: Tag-Upload-PyPI

on:
  push:
    tags:
      - '*'

jobs:
  publish-pypi-test:
    name: Build and Publish to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5

      - name: Build wheel and sdist
        run: uv build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  install-pypi-test:
    name: Install from Test PyPI
    needs: publish-pypi-test
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/setup-uv@v5
      - name: pip install dendri from Test PyPI
        run: >-
          uv pip install
          --index-url https://test.pypi.org/simple
          --extra-index-url https://pypi.org/simple
          dendri
      - name: Test dendri install
        run: uv run python -c "import dendri"

  publish-pypi-prod:
    name: Build and Publish to Prod PyPI
    needs: install-pypi-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5

      - name: Build wheel and sdist
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  install-pypi-prod:
    name: Install from Prod PyPI
    needs: publish-pypi-prod
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/setup-uv@v5
      - name: pip install dendri
        run: uv pip install dendri
      - name: Test dendri install
        run: uv run python -c "import dendri"
